#!/bin/sh

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.scripts/:$PATH
export PATH=$HOME/.local/share/neovim/bin:$PATH
export PATH=$HOME:/home/bryant/.local/share/bob/nvim-bin:$PATH
export PATH=$HOME:/home/bryant/.spicetify:$PATH
export PATH=$HOME:~/.local/share/nvim/mason/bin:$PATH
export PATH=$HOME:/home/bryant/.config/local/share/nvim/mason/bin:$PATH
export GPG_TTY=$(tty)
export PATH=~/.npm-global/bin:$PATH
export GOPATH=$HOME/go
# export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
export PATH=$PATH:/home/bryant/.local/share/gem/ruby/3.0.0/bin:$PATH
export PATH=$PATH:/home/bryant/.cargo/bin:$PATH
export PATH=$PATH:/home/bryant/Dev/Clone/swww/target/release/:$PATH
# export PATH=$PATH:/usr/bin/dart:
# ~/.tmux/plugins
export PATH=$HOME/.tmux/plugins/t-smart-tmux-session-manager/bin:$PATH
# ~/.config/tmux/plugins
export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH
# export PATH=$HOME/conda/etc/profile.d/conda.sh:$PATH
# export PATH=$HOME/conda/etc/profile.d/mamba.sh:$PATH

# everblush
# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#232a2d,bg:#141b1e,spinner:#e5c76b,hl:#e57474 \
# --color=fg:#dadada,header:#e57474,info:#c47fd5,pointer:#e5c76b \
# --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#c47fd5,hl+:#f38ba8"

# mocha
# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
# --color=fg:#cdd6f4,header:italic:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
# --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:#cdd6f4,fg+:#c6d0f5,bg:#1e1e2e,bg+:#313244
  --color=hl:#d0cccc,hl+:#81c8be,info:#ca9ee6,marker:#ef9f76
  --color=prompt:#f4b8e4,spinner:#af5fff,pointer:#eb696b,header:#87afaf
  --color=border:#1e1e2e,preview-border:#7dc4e4,preview-label:#513434,label:#7dc4e4
  --color=query:#cdd6f4
  --border="rounded" --border-label="   ~ Result ~   " --border-label-pos="0" --preview-window="border-rounded"
  --prompt="> " --marker=">" --pointer=">" --separator=""
  --scrollbar="│"'


# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#3c474d,bg:#1b2124,spinner:#d3b884,hl:#e68183 \
# --color=fg:#dad0bc,header:#e68183,info:#d699b6,pointer:#d3c5aa \
# --color=marker:#f5e0dc,fg+:#dad0bc,prompt:#d699b6,hl+:#e68183"
