notARepository: "create"

os:
  edit: "nvim" # see 'Configuring File Editing' section
  editAtLine: "{{editor}} {{filename}}"
  openCommand: ""
keybinding:
  universal:
    pushFiles: "p"
    pullFiles: "P"
customCommands:
  - key: <c-q>
    command: 'git commit -a --allow-empty-message -m ""'
    context: global
    description: Empty commit
    loadingText: Pushing...
  - key: "a"
    command: "git {{if .SelectedFile.HasUnstagedChanges}} add {{else}} reset {{end}} {{.SelectedFile.Name}}"
    context: "files"
    description: "toggle file staged"
gui:
  # use the mocha catppuccin theme
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
