notARepository: "create"

os:
  edit: "nvim" # see 'Configuring File Editing' section
  editAtLine: "{{editor}} {{filename}}"
  openCommand: ""
keybinding:
  universal:
    pushFiles: "p"
    pullFiles: "P"
customCommands:
  - key: <c-q>
    command: 'git commit -a --allow-empty-message -m ""'
    context: global
    description: Empty commit
    loadingText: Pushing...
  - key: "a"
    command: "git {{if .SelectedFile.HasUnstagedChanges}} add {{else}} reset {{end}} {{.SelectedFile.Name}}"
    context: "files"
    description: "toggle file staged"
# gui:
#   # use the mocha catppuccin theme
#   theme:
#     activeBorderColor:
#       - "#a6e3a1"
#       - bold
#     inactiveBorderColor:
#       - "#a6adc8"
#     optionsTextColor:
#       - "#89b4fa"
#     selectedLineBgColor:
#       - "#313244"
#     cherryPickedCommitBgColor:
#       - "#45475a"
#     cherryPickedCommitFgColor:
#       - "#a6e3a1"
#     unstagedChangesColor:
#       - "#f38ba8"
#     defaultFgColor:
#       - "#cdd6f4"
#     searchingActiveBorderColor:
#       - "#f9e2af"

#   authorColors:
#     "*": "#b4befe"
